version: "3"

services:
  mongo:
    image: mongo:5.0.2
    restart: "unless-stopped"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_talent_forest:/data/db

volumes:
  mongodb_talent_forest:
