version: "3"

services:
  mongo:
    image: mongo:5.0.2
    restart: "unless-stopped"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_talent_forest:/data/db

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: root
    ports:
      - 5432:5432
    volumes:
      - postgres_talent_forest:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_talent_forest:/data

volumes:
  mongodb_talent_forest:
  postgres_talent_forest:
  redis_talent_forest:
